import psycopg2


def insert_codPaises_iso_3166(cursor):
    
    cursor.execute('''                             
            INSERT INTO iso_3166_1 (code, country_name, year) VALUES
            ('AD', 'Andorra', 1974),
            ('AE', 'Emirados Árabes Unidos', 1974),
            ('AF', 'Afeganistão', 1974),
            ('AG', 'Antígua e Barbuda', 1974),
            ('AI', 'Anguila', 1985),
            ('AL', 'Albânia', 1974),
            ('AM', 'Armênia', 1992),
            ('AO', 'Angola', 1974),
            ('AQ', 'Antártica', 1974),
            ('AR', 'Argentina', 1974),
            ('AS', 'Samoa Americana', 1974),
            ('AT', 'Áustria', 1974),
            ('AU', 'Austrália', 1974),
            ('AW', 'Aruba', 1986),
            ('AX', 'Ilhas Åland', 2004),
            ('AZ', 'Azerbaijão', 1992),
            ('BA', 'Bósnia e Herzegovina', 1992),
            ('BB', 'Barbados', 1974),
            ('BD', 'Bangladesh', 1974),
            ('BE', 'Bélgica', 1974),
            ('BF', 'Burkina Faso', 1984),
            ('BG', 'Bulgária', 1974),
            ('BH', 'Bahrein', 1974),
            ('BI', 'Burundi', 1974),
            ('BJ', 'Benin', 1977),
            ('BL', 'São Bartolomeu', 2007),
            ('BM', 'Bermudas', 1974),
            ('BN', 'Brunei Darussalam', 1974),
            ('BO', 'Bolívia, Estado Plurinacional de', 1974),
            ('BQ', 'Bonaire, Santo Eustáquio e Saba', 2010),
            ('BR', 'Brasil', 1974),
            ('BS', 'Bahamas', 1974),
            ('BT', 'Butão', 1974),
            ('BV', 'Ilha Bouvet', 1974),
            ('BW', 'Botswana', 1974),
            ('BY', 'Bielorrússia', 1974),
            ('BZ', 'Belize', 1974),
            ('CA', 'Canadá', 1974),
            ('CC', 'Ilhas Cocos (Keeling)', 1974),
            ('CD', 'Congo, República Democrática do', 1997),
            ('CF', 'República Centro-Africana', 1974),
            ('CG', 'Congo', 1974),
            ('CH', 'Suíça', 1974),
            ('CI', 'Costa do Marfim', 1974),
            ('CK', 'Ilhas Cook', 1974),
            ('CL', 'Chile', 1974),
            ('CM', 'Camarões', 1974),
            ('CN', 'China', 1974),
            ('CO', 'Colômbia', 1974),
            ('CR', 'Costa Rica', 1974),
            ('CU', 'Cuba', 1974),
            ('CV', 'Cabo Verde', 1974),
            ('CW', 'Curaçao', 2010),
            ('CX', 'Ilha Christmas', 1974),
            ('CY', 'Chipre', 1974),
            ('CZ', 'Tchéquia', 1993),
            ('DE', 'Alemanha', 1974),
            ('DJ', 'Djibuti', 1977),
            ('DK', 'Dinamarca', 1974),
            ('DM', 'Dominica', 1974),
            ('DO', 'República Dominicana', 1974),
            ('DZ', 'Argélia', 1974),
            ('EC', 'Equador', 1974),
            ('EE', 'Estônia', 1992),
            ('EG', 'Egito', 1974),
            ('EH', 'Saara Ocidental', 1974),
            ('ER', 'Eritreia', 1993),
            ('ES', 'Espanha', 1974),
            ('ET', 'Etiópia', 1974),
            ('FI', 'Finlândia', 1974),
            ('FJ', 'Fiji', 1974),
            ('FK', 'Ilhas Falkland (Malvinas)', 1974),
            ('FM', 'Micronésia, Estados Federados da', 1986),
            ('FO', 'Ilhas Faroe', 1974),
            ('FR', 'França', 1974),
            ('GA', 'Gabão', 1974),
            ('GB', 'Reino Unido da Grã-Bretanha e Irlanda do Norte', 1974),
            ('GD', 'Granada', 1974),
            ('GE', 'Geórgia', 1992),
            ('GF', 'Guiana Francesa', 1974),
            ('GG', 'Guernsey', 2006),
            ('GH', 'Gana', 1974),
            ('GI', 'Gibraltar', 1974),
            ('GL', 'Groenlândia', 1974),
            ('GM', 'Gâmbia', 1974),
            ('GN', 'Guiné', 1974),
            ('GP', 'Guadalupe', 1974),
            ('GQ', 'Guiné Equatorial', 1974),
            ('GR', 'Grécia', 1974),
            ('GS', 'Geórgia do Sul e Ilhas Sandwich do Sul', 1993),
            ('GT', 'Guatemala', 1974),
            ('GU', 'Guam', 1974),
            ('GW', 'Guiné-Bissau', 1974),
            ('GY', 'Guiana', 1974),
            ('HK', 'Hong Kong', 1974),
            ('HM', 'Ilha Heard e Ilhas McDonald', 1974),
            ('HN', 'Honduras', 1974),
            ('HR', 'Croácia', 1992),
            ('HT', 'Haiti', 1974),
            ('HU', 'Hungria', 1974),
            ('ID', 'Indonésia', 1974),
            ('IE', 'Irlanda', 1974),
            ('IL', 'Israel', 1974),
            ('IM', 'Ilha de Man', 2006),
            ('IN', 'Índia', 1974),
            ('IO', 'Território Britânico do Oceano Índico', 1974),
            ('IQ', 'Iraque', 1974),
            ('IR', 'Irã, República Islâmica do', 1974),
            ('IS', 'Islândia', 1974),
            ('IT', 'Itália', 1974),
            ('JE', 'Jersey', 2006),
            ('JM', 'Jamaica', 1974),
            ('JO', 'Jordânia', 1974),
            ('JP', 'Japão', 1974),
            ('KE', 'Quênia', 1974),
            ('KG', 'Quirguistão', 1992),
            ('KH', 'Camboja', 1974),
            ('KI', 'Quiribati', 1979),
            ('KM', 'Comores', 1974),
            ('KN', 'São Cristóvão e Nevis', 1974),
            ('KP', 'Coreia, República Popular Democrática da', 1974),
            ('KR', 'Coreia, República da', 1974),
            ('KW', 'Kuwait', 1974),
            ('KY', 'Ilhas Cayman', 1974),
            ('KZ', 'Cazaquistão', 1992),
            ('LA', 'República Democrática Popular do Laos', 1974),
            ('LB', 'Líbano', 1974),
            ('LC', 'Santa Lúcia', 1974),
            ('LI', 'Liechtenstein', 1974),
            ('LK', 'Sri Lanka', 1974),
            ('LR', 'Libéria', 1974),
            ('LS', 'Lesoto', 1974),
            ('LT', 'Lituânia', 1992),
            ('LU', 'Luxemburgo', 1974),
            ('LV', 'Letônia', 1992),
            ('LY', 'Líbia', 1974),
            ('MA', 'Marrocos', 1974),
            ('MC', 'Mônaco', 1974),
            ('MD', 'Moldávia, República da', 1992),
            ('ME', 'Montenegro', 2006),
            ('MF', 'São Martinho (parte francesa)', 2007),
            ('MG', 'Madagáscar', 1974),
            ('MH', 'Ilhas Marshall', 1986),
            ('MK', 'Macedônia do Norte', 1993),
            ('ML', 'Mali', 1974),
            ('MM', 'Mianmar', 1989),
            ('MN', 'Mongólia', 1974),
            ('MO', 'Macau', 1974),
            ('MP', 'Ilhas Marianas do Norte', 1986),
            ('MQ', 'Martinica', 1974),
            ('MR', 'Mauritânia', 1974),
            ('MS', 'Montserrat', 1974),
            ('MT', 'Malta', 1974),
            ('MU', 'Maurício', 1974),
            ('MV', 'Maldivas', 1974),
            ('MW', 'Malaui', 1974),
            ('MX', 'México', 1974),
            ('MY', 'Malásia', 1974),
            ('MZ', 'Moçambique', 1974),
            ('NA', 'Namíbia', 1974),
            ('NC', 'Nova Caledônia', 1974),
            ('NE', 'Níger', 1974),
            ('NF', 'Ilha Norfolk', 1974),
            ('NG', 'Nigéria', 1974),
            ('NI', 'Nicarágua', 1974),
            ('NL', 'Países Baixos', 1974),
            ('NO', 'Noruega', 1974),
            ('NP', 'Nepal', 1974),
            ('NR', 'Nauru', 1974),
            ('NU', 'Niue', 1974),
            ('NZ', 'Nova Zelândia', 1974),
            ('OM', 'Omã', 1974),
            ('PA', 'Panamá', 1974),
            ('PE', 'Peru', 1974),
            ('PF', 'Polinésia Francesa', 1974),
            ('PG', 'Papua Nova Guiné', 1974),
            ('PH', 'Filipinas', 1974),
            ('PK', 'Paquistão', 1974),
            ('PL', 'Polônia', 1974),
            ('PM', 'Saint Pierre e Miquelon', 1974),
            ('PN', 'Pitcairn', 1974),
            ('PR', 'Porto Rico', 1974),
            ('PS', 'Palestina, Estado de', 1999),
            ('PT', 'Portugal', 1974),
            ('PW', 'Palau', 1986),
            ('PY', 'Paraguai', 1974),
            ('QA', 'Catar', 1974),
            ('RE', 'Reunião', 1974),
            ('RO', 'Romênia', 1974),
            ('RS', 'Sérvia', 2006),
            ('RU', 'Federação Russa', 1992),
            ('RW', 'Ruanda', 1974),
            ('SA', 'Arábia Saudita', 1974),
            ('SB', 'Ilhas Salomão', 1974),
            ('SC', 'Seicheles', 1974),
            ('SD', 'Sudão', 1974),
            ('SE', 'Suécia', 1974),
            ('SG', 'Cingapura', 1974),
            ('SH', 'Santa Helena, Ascensão e Tristão da Cunha', 1974),
            ('SI', 'Eslovênia', 1992),
            ('SJ', 'Svalbard e Jan Mayen', 1974),
            ('SK', 'Eslováquia', 1993),
            ('SL', 'Serra Leoa', 1974),
            ('SM', 'San Marino', 1974),
            ('SN', 'Senegal', 1974),
            ('SO', 'Somália', 1974),
            ('SR', 'Suriname', 1974),
            ('SS', 'Sudão do Sul', 2011),
            ('ST', 'São Tomé e Príncipe', 1974),
            ('SV', 'El Salvador', 1974),
            ('SX', 'Sint Maarten (parte holandesa)', 2010),
            ('SY', 'República Árabe da Síria', 1974),
            ('SZ', 'Eswatini', 1974),
            ('TC', 'Ilhas Turks e Caicos', 1974),
            ('TD', 'Chade', 1974),
            ('TF', 'Territórios Franceses do Sul', 1979),
            ('TG', 'Togo', 1974),
            ('TH', 'Tailândia', 1974),
            ('TJ', 'Tadjiquistão', 1992),
            ('TK', 'Toquelau', 1974),
            ('TL', 'Timor-Leste', 2002),
            ('TM', 'Turcomenistão', 1992),
            ('TN', 'Tunísia', 1974),
            ('TO', 'Tonga', 1974),
            ('TR', 'Turquia', 1974),
            ('TT', 'Trindade e Tobago', 1974),
            ('TV', 'Tuvalu', 1977),
            ('TW', 'Taiwan, Província da China', 1974),
            ('TZ', 'Tanzânia, República Unida da', 1974),
            ('UA', 'Ucrânia', 1974),
            ('UG', 'Uganda', 1974),
            ('UM', 'Ilhas Menores Distantes dos Estados Unidos', 1986),
            ('US', 'Estados Unidos da América', 1974),
            ('UY', 'Uruguai', 1974),
            ('UZ', 'Uzbequistão', 1992),
            ('VA', 'Santa Sé', 1974),
            ('VC', 'São Vicente e Granadinas', 1974),
            ('VE', 'Venezuela, República Bolivariana da', 1974),
            ('VG', 'Ilhas Virgens (Britânicas)', 1974),
            ('VI', 'Ilhas Virgens (EUA)', 1974),
            ('VN', 'Vietnã', 1974),
            ('VU', 'Vanuatu', 1980),
            ('WF', 'Wallis e Futuna', 1974),
            ('WS', 'Samoa', 1974),
            ('YE', 'Iémen', 1974),
            ('YT', 'Mayotte', 1993),
            ('ZA', 'África do Sul', 1974),
            ('ZM', 'Zâmbia', 1974),
            ('ZW', 'Zimbábue', 1980);
            ''',)
    print("Códigos de países inseridos com sucesso!")
    